version: 0.2

phases:

  install:
    commands:
      - echo "Installing Build Environment"

  pre_build:
    commands:
      - echo "Running Validation"

  build:
    commands:
      - echo "Packaging Application"

  post_build:
    commands:
      - echo "Build Completed Successfully"

artifacts:
  files:
    - '**/*'
